# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\sinca\Downloads\codify

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\sinca\Downloads\codify

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\sinca\Downloads\codify\CMakeFiles C:\Users\sinca\Downloads\codify\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\sinca\Downloads\codify\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named codify

# Build rule for target.
codify: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 codify
.PHONY : codify

# fast build rule for target.
codify/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/build
.PHONY : codify/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f lib\glfw\CMakeFiles\uninstall.dir\build.make lib/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f lib\glfw\src\CMakeFiles\glfw.dir\build.make lib/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f lib\glfw\src\CMakeFiles\update_mappings.dir\build.make lib/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

codecs/eclcrypt/eclcrypt.obj: codecs/eclcrypt/eclcrypt.c.obj
.PHONY : codecs/eclcrypt/eclcrypt.obj

# target to build an object file
codecs/eclcrypt/eclcrypt.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/codecs/eclcrypt/eclcrypt.c.obj
.PHONY : codecs/eclcrypt/eclcrypt.c.obj

codecs/eclcrypt/eclcrypt.i: codecs/eclcrypt/eclcrypt.c.i
.PHONY : codecs/eclcrypt/eclcrypt.i

# target to preprocess a source file
codecs/eclcrypt/eclcrypt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/codecs/eclcrypt/eclcrypt.c.i
.PHONY : codecs/eclcrypt/eclcrypt.c.i

codecs/eclcrypt/eclcrypt.s: codecs/eclcrypt/eclcrypt.c.s
.PHONY : codecs/eclcrypt/eclcrypt.s

# target to generate assembly for a file
codecs/eclcrypt/eclcrypt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/codecs/eclcrypt/eclcrypt.c.s
.PHONY : codecs/eclcrypt/eclcrypt.c.s

codecs/pigl/pigl.obj: codecs/pigl/pigl.c.obj
.PHONY : codecs/pigl/pigl.obj

# target to build an object file
codecs/pigl/pigl.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/codecs/pigl/pigl.c.obj
.PHONY : codecs/pigl/pigl.c.obj

codecs/pigl/pigl.i: codecs/pigl/pigl.c.i
.PHONY : codecs/pigl/pigl.i

# target to preprocess a source file
codecs/pigl/pigl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/codecs/pigl/pigl.c.i
.PHONY : codecs/pigl/pigl.c.i

codecs/pigl/pigl.s: codecs/pigl/pigl.c.s
.PHONY : codecs/pigl/pigl.s

# target to generate assembly for a file
codecs/pigl/pigl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/codecs/pigl/pigl.c.s
.PHONY : codecs/pigl/pigl.c.s

codecs/ubdb/ubdb.obj: codecs/ubdb/ubdb.c.obj
.PHONY : codecs/ubdb/ubdb.obj

# target to build an object file
codecs/ubdb/ubdb.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/codecs/ubdb/ubdb.c.obj
.PHONY : codecs/ubdb/ubdb.c.obj

codecs/ubdb/ubdb.i: codecs/ubdb/ubdb.c.i
.PHONY : codecs/ubdb/ubdb.i

# target to preprocess a source file
codecs/ubdb/ubdb.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/codecs/ubdb/ubdb.c.i
.PHONY : codecs/ubdb/ubdb.c.i

codecs/ubdb/ubdb.s: codecs/ubdb/ubdb.c.s
.PHONY : codecs/ubdb/ubdb.s

# target to generate assembly for a file
codecs/ubdb/ubdb.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/codecs/ubdb/ubdb.c.s
.PHONY : codecs/ubdb/ubdb.c.s

includes/backend.obj: includes/backend.c.obj
.PHONY : includes/backend.obj

# target to build an object file
includes/backend.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/includes/backend.c.obj
.PHONY : includes/backend.c.obj

includes/backend.i: includes/backend.c.i
.PHONY : includes/backend.i

# target to preprocess a source file
includes/backend.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/includes/backend.c.i
.PHONY : includes/backend.c.i

includes/backend.s: includes/backend.c.s
.PHONY : includes/backend.s

# target to generate assembly for a file
includes/backend.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/includes/backend.c.s
.PHONY : includes/backend.c.s

lib/imgui/backends/imgui_impl_glfw.obj: lib/imgui/backends/imgui_impl_glfw.cpp.obj
.PHONY : lib/imgui/backends/imgui_impl_glfw.obj

# target to build an object file
lib/imgui/backends/imgui_impl_glfw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/lib/imgui/backends/imgui_impl_glfw.cpp.obj
.PHONY : lib/imgui/backends/imgui_impl_glfw.cpp.obj

lib/imgui/backends/imgui_impl_glfw.i: lib/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : lib/imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
lib/imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/lib/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : lib/imgui/backends/imgui_impl_glfw.cpp.i

lib/imgui/backends/imgui_impl_glfw.s: lib/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : lib/imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
lib/imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/lib/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : lib/imgui/backends/imgui_impl_glfw.cpp.s

lib/imgui/backends/imgui_impl_opengl3.obj: lib/imgui/backends/imgui_impl_opengl3.cpp.obj
.PHONY : lib/imgui/backends/imgui_impl_opengl3.obj

# target to build an object file
lib/imgui/backends/imgui_impl_opengl3.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/lib/imgui/backends/imgui_impl_opengl3.cpp.obj
.PHONY : lib/imgui/backends/imgui_impl_opengl3.cpp.obj

lib/imgui/backends/imgui_impl_opengl3.i: lib/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : lib/imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
lib/imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/lib/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : lib/imgui/backends/imgui_impl_opengl3.cpp.i

lib/imgui/backends/imgui_impl_opengl3.s: lib/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : lib/imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
lib/imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/lib/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : lib/imgui/backends/imgui_impl_opengl3.cpp.s

lib/imgui/imgui.obj: lib/imgui/imgui.cpp.obj
.PHONY : lib/imgui/imgui.obj

# target to build an object file
lib/imgui/imgui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/lib/imgui/imgui.cpp.obj
.PHONY : lib/imgui/imgui.cpp.obj

lib/imgui/imgui.i: lib/imgui/imgui.cpp.i
.PHONY : lib/imgui/imgui.i

# target to preprocess a source file
lib/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/lib/imgui/imgui.cpp.i
.PHONY : lib/imgui/imgui.cpp.i

lib/imgui/imgui.s: lib/imgui/imgui.cpp.s
.PHONY : lib/imgui/imgui.s

# target to generate assembly for a file
lib/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/lib/imgui/imgui.cpp.s
.PHONY : lib/imgui/imgui.cpp.s

lib/imgui/imgui_demo.obj: lib/imgui/imgui_demo.cpp.obj
.PHONY : lib/imgui/imgui_demo.obj

# target to build an object file
lib/imgui/imgui_demo.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/lib/imgui/imgui_demo.cpp.obj
.PHONY : lib/imgui/imgui_demo.cpp.obj

lib/imgui/imgui_demo.i: lib/imgui/imgui_demo.cpp.i
.PHONY : lib/imgui/imgui_demo.i

# target to preprocess a source file
lib/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/lib/imgui/imgui_demo.cpp.i
.PHONY : lib/imgui/imgui_demo.cpp.i

lib/imgui/imgui_demo.s: lib/imgui/imgui_demo.cpp.s
.PHONY : lib/imgui/imgui_demo.s

# target to generate assembly for a file
lib/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/lib/imgui/imgui_demo.cpp.s
.PHONY : lib/imgui/imgui_demo.cpp.s

lib/imgui/imgui_draw.obj: lib/imgui/imgui_draw.cpp.obj
.PHONY : lib/imgui/imgui_draw.obj

# target to build an object file
lib/imgui/imgui_draw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/lib/imgui/imgui_draw.cpp.obj
.PHONY : lib/imgui/imgui_draw.cpp.obj

lib/imgui/imgui_draw.i: lib/imgui/imgui_draw.cpp.i
.PHONY : lib/imgui/imgui_draw.i

# target to preprocess a source file
lib/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/lib/imgui/imgui_draw.cpp.i
.PHONY : lib/imgui/imgui_draw.cpp.i

lib/imgui/imgui_draw.s: lib/imgui/imgui_draw.cpp.s
.PHONY : lib/imgui/imgui_draw.s

# target to generate assembly for a file
lib/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/lib/imgui/imgui_draw.cpp.s
.PHONY : lib/imgui/imgui_draw.cpp.s

lib/imgui/imgui_tables.obj: lib/imgui/imgui_tables.cpp.obj
.PHONY : lib/imgui/imgui_tables.obj

# target to build an object file
lib/imgui/imgui_tables.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/lib/imgui/imgui_tables.cpp.obj
.PHONY : lib/imgui/imgui_tables.cpp.obj

lib/imgui/imgui_tables.i: lib/imgui/imgui_tables.cpp.i
.PHONY : lib/imgui/imgui_tables.i

# target to preprocess a source file
lib/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/lib/imgui/imgui_tables.cpp.i
.PHONY : lib/imgui/imgui_tables.cpp.i

lib/imgui/imgui_tables.s: lib/imgui/imgui_tables.cpp.s
.PHONY : lib/imgui/imgui_tables.s

# target to generate assembly for a file
lib/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/lib/imgui/imgui_tables.cpp.s
.PHONY : lib/imgui/imgui_tables.cpp.s

lib/imgui/imgui_widgets.obj: lib/imgui/imgui_widgets.cpp.obj
.PHONY : lib/imgui/imgui_widgets.obj

# target to build an object file
lib/imgui/imgui_widgets.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/lib/imgui/imgui_widgets.cpp.obj
.PHONY : lib/imgui/imgui_widgets.cpp.obj

lib/imgui/imgui_widgets.i: lib/imgui/imgui_widgets.cpp.i
.PHONY : lib/imgui/imgui_widgets.i

# target to preprocess a source file
lib/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/lib/imgui/imgui_widgets.cpp.i
.PHONY : lib/imgui/imgui_widgets.cpp.i

lib/imgui/imgui_widgets.s: lib/imgui/imgui_widgets.cpp.s
.PHONY : lib/imgui/imgui_widgets.s

# target to generate assembly for a file
lib/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/lib/imgui/imgui_widgets.cpp.s
.PHONY : lib/imgui/imgui_widgets.cpp.s

src/cli.obj: src/cli.c.obj
.PHONY : src/cli.obj

# target to build an object file
src/cli.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/src/cli.c.obj
.PHONY : src/cli.c.obj

src/cli.i: src/cli.c.i
.PHONY : src/cli.i

# target to preprocess a source file
src/cli.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/src/cli.c.i
.PHONY : src/cli.c.i

src/cli.s: src/cli.c.s
.PHONY : src/cli.s

# target to generate assembly for a file
src/cli.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/src/cli.c.s
.PHONY : src/cli.c.s

src/main.obj: src/main.c.obj
.PHONY : src/main.obj

# target to build an object file
src/main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/src/main.c.obj
.PHONY : src/main.c.obj

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/src/main.c.s
.PHONY : src/main.c.s

src/window.obj: src/window.cpp.obj
.PHONY : src/window.obj

# target to build an object file
src/window.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/src/window.cpp.obj
.PHONY : src/window.cpp.obj

src/window.i: src/window.cpp.i
.PHONY : src/window.i

# target to preprocess a source file
src/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/src/window.cpp.i
.PHONY : src/window.cpp.i

src/window.s: src/window.cpp.s
.PHONY : src/window.s

# target to generate assembly for a file
src/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\codify.dir\build.make CMakeFiles/codify.dir/src/window.cpp.s
.PHONY : src/window.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... rebuild_cache
	@echo ... uninstall
	@echo ... update_mappings
	@echo ... codify
	@echo ... glfw
	@echo ... codecs/eclcrypt/eclcrypt.obj
	@echo ... codecs/eclcrypt/eclcrypt.i
	@echo ... codecs/eclcrypt/eclcrypt.s
	@echo ... codecs/pigl/pigl.obj
	@echo ... codecs/pigl/pigl.i
	@echo ... codecs/pigl/pigl.s
	@echo ... codecs/ubdb/ubdb.obj
	@echo ... codecs/ubdb/ubdb.i
	@echo ... codecs/ubdb/ubdb.s
	@echo ... includes/backend.obj
	@echo ... includes/backend.i
	@echo ... includes/backend.s
	@echo ... lib/imgui/backends/imgui_impl_glfw.obj
	@echo ... lib/imgui/backends/imgui_impl_glfw.i
	@echo ... lib/imgui/backends/imgui_impl_glfw.s
	@echo ... lib/imgui/backends/imgui_impl_opengl3.obj
	@echo ... lib/imgui/backends/imgui_impl_opengl3.i
	@echo ... lib/imgui/backends/imgui_impl_opengl3.s
	@echo ... lib/imgui/imgui.obj
	@echo ... lib/imgui/imgui.i
	@echo ... lib/imgui/imgui.s
	@echo ... lib/imgui/imgui_demo.obj
	@echo ... lib/imgui/imgui_demo.i
	@echo ... lib/imgui/imgui_demo.s
	@echo ... lib/imgui/imgui_draw.obj
	@echo ... lib/imgui/imgui_draw.i
	@echo ... lib/imgui/imgui_draw.s
	@echo ... lib/imgui/imgui_tables.obj
	@echo ... lib/imgui/imgui_tables.i
	@echo ... lib/imgui/imgui_tables.s
	@echo ... lib/imgui/imgui_widgets.obj
	@echo ... lib/imgui/imgui_widgets.i
	@echo ... lib/imgui/imgui_widgets.s
	@echo ... src/cli.obj
	@echo ... src/cli.i
	@echo ... src/cli.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/window.obj
	@echo ... src/window.i
	@echo ... src/window.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

